services:
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\JsonRPCEndpointBundle\Service\:
    resource: '../../Service/'
  Tourze\JsonRPCEndpointBundle\Procedure\:
    resource: '../../Procedure/'

  Tourze\JsonRPC\Core\Serialization\JsonRpcCallDenormalizer: ~
  Tourze\JsonRPC\Core\Serialization\JsonRpcCallResponseNormalizer: ~
  Tourze\JsonRPC\Core\Serialization\JsonRpcCallSerializer: ~
  Tourze\JsonRPC\Core\Serialization\JsonRpcRequestDenormalizer: ~
  Tourze\JsonRPC\Core\Serialization\JsonRpcResponseNormalizer: ~
